module.exports = {
  backend_user: {
    type_code: 'backend_user',
    version: '0.1',
    name: 'Backend User',
    instantiable: '1',
    allowed_access: 'system_user',
    parent_type: 'user',
    dir: 'core/assets/users/backend_user',
    customisation: '0',
    description: 'Backend Users are the only users that have access to the backend',
    lvl: '2'
  },
  bulkmail_job: {
    type_code: 'bulkmail_job',
    version: '0.1',
    name: 'Bulkmail Job',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'bulkmail_post_office',
    dir: 'packages/bulkmail/bulkmail_job',
    customisation: '0',
    description: 'Bulkmail Jobs are used to send bulk emails. They use the methods defined in their parent Post Office to deliver the mail.',
    lvl: '2'
  },
  bulkmail_post_office: {
    type_code: 'bulkmail_post_office',
    version: '0.2',
    name: 'Bulkmail Post Office',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/bulkmail/bulkmail_post_office',
    customisation: '0',
    description: 'The post office defines which email server the child bulkmail jobs will be delivered to.',
    lvl: '1'
  },
  bulkmail_subscribe_page: {
    type_code: 'bulkmail_subscribe_page',
    version: '0.1',
    name: 'Bulkmail Subscribe Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_user_group_manager',
    dir: 'packages/bulkmail/bulkmail_subscribe_page',
    customisation: '0',
    description: 'Provides the frontend ability to subscribe / unsubscribe users from bulkmail groups',
    lvl: '3'
  },
  bulkmail_user: {
    type_code: 'bulkmail_user',
    version: '0.1',
    name: 'Bulkmail User',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/bulkmail/bulkmail_user',
    customisation: '0',
    description: 'Bulkmail users are simple users with a unique email address and name',
    lvl: '1'
  },
  calendar_event_cancellation: {
    type_code: 'calendar_event_cancellation',
    version: '0.2',
    name: 'Recurring Event Cancellation',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'calendar_event',
    dir: 'packages/calendar/calendar_events/calendar_event_cancellation',
    customisation: '0',
    description: 'Describes a situation where an instance of a recurring event is cancelled',
    lvl: '2'
  },
  calendar_event_modification: {
    type_code: 'calendar_event_modification',
    version: '0.2',
    name: 'Recurring Event Modification',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'calendar_event',
    dir: 'packages/calendar/calendar_events/calendar_event_modification',
    customisation: '0',
    description: 'Describes an instance of a recurring event whose name or description are different to the usual details',
    lvl: '2'
  },
  calendar_event_multi_date: {
    type_code: 'calendar_event_multi_date',
    version: '0.1',
    name: 'Multi-Date Calendar Event',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/calendar/calendar_events/calendar_event_multi_date',
    customisation: '0',
    description: 'Allows multiple Single and Recurring Calendar instances to be combined under one event',
    lvl: '1'
  },
  calendar_event_recurring: {
    type_code: 'calendar_event_recurring',
    version: '0.2',
    name: 'Recurring Calendar Event',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'calendar_event',
    dir: 'packages/calendar/calendar_events/calendar_event_recurring',
    customisation: '0',
    description: 'Describes an event in time that recurs according to a given schedule.',
    lvl: '2'
  },
  calendar_event_single: {
    type_code: 'calendar_event_single',
    version: '0.2',
    name: 'Single Calendar Event',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'calendar_event',
    dir: 'packages/calendar/calendar_events/calendar_event_single',
    customisation: '0',
    description: 'Describes an event that occurs only once',
    lvl: '2'
  },
  cmis_bridge: {
    type_code: 'cmis_bridge',
    version: '0.1',
    name: 'CMIS Bridge',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/sharepoint/cmis_bridge',
    customisation: '0',
    description: 'Creates file assets under itself in synchronization with a repository having a CMIS Connector such as MS Sharepoint',
    lvl: '1'
  },
  comment: {
    type_code: 'comment',
    version: '0.11',
    name: 'Comment',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/news/comment',
    customisation: '0',
    description: 'Comment',
    lvl: '2'
  },
  css_file: {
    type_code: 'css_file',
    version: '0.1',
    name: 'CSS File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/css_file',
    customisation: '0',
    description: 'Specialised type of File asset for CSS Files',
    lvl: '2'
  },
  data_record: {
    type_code: 'data_record',
    version: '0.1',
    name: 'Data Record',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/data_source/data_record',
    customisation: '0',
    description: 'Data Record lets you have metadata.',
    lvl: '1'
  },
  data_source_csv: {
    type_code: 'data_source_csv',
    version: '0.1',
    name: 'CSV Data Source',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/data/data_source_csv',
    customisation: '0',
    description: 'This is used to expose assets from data stored in a CSV file',
    lvl: '2'
  },
  data_source_db: {
    type_code: 'data_source_db',
    version: '0.4',
    name: 'DB Data Source',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/data/data_source_db',
    customisation: '0',
    description: 'This is used to establish connectivity with a DB',
    lvl: '2'
  },
  data_source_graph: {
    type_code: 'data_source_graph',
    version: '0.1',
    name: 'Data Source Graph',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'image',
    dir: 'packages/data/data_source_graph',
    customisation: '0',
    description: 'You can choose a datsource for this asset and it draws a Graph with the specifid co-ordinates',
    lvl: '3'
  },
  data_source_ical: {
    type_code: 'data_source_ical',
    version: '0.1',
    name: 'iCal Data Source',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/data/data_source_ical',
    customisation: '0',
    description: 'Read an iCal format feed',
    lvl: '2'
  },
  data_source_json: {
    type_code: 'data_source_json',
    version: '0.1',
    name: 'JSON Data Source',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/data/data_source_json',
    customisation: '0',
    description: 'Converts JSON data to assets',
    lvl: '2'
  },
  data_source_ldap: {
    type_code: 'data_source_ldap',
    version: '0.1',
    name: 'LDAP Data Source',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/data/data_source_ldap',
    customisation: '0',
    description: 'Provides ability to create shadow assets from LDAP directory',
    lvl: '2'
  },
  data_source_rss: {
    type_code: 'data_source_rss',
    version: '0.2',
    name: 'RSS Data Source',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/data/data_source_rss',
    customisation: '0',
    description: 'This is used to Read The RSS Feeds',
    lvl: '2'
  },
  data_source_soap: {
    type_code: 'data_source_soap',
    version: '0.1',
    name: 'SOAP Data Source',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/web_services/api/data_source_soap',
    customisation: '0',
    description: 'Provides ability to create shadow assets based on the response from the SOAP Service',
    lvl: '2'
  },
  data_source_xml: {
    type_code: 'data_source_xml',
    version: '0.3',
    name: 'XML Data Source',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/data/data_source_xml',
    customisation: '0',
    description: 'Provides ability to create shadow assets from any XML source',
    lvl: '2'
  },
  db_connector: {
    type_code: 'db_connector',
    version: '0.1',
    name: 'DB Connector',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/data/db_connector',
    customisation: '0',
    description: 'Used by DB data sources to store DB connection settings and construct the DB object',
    lvl: '1'
  },
  default_delivery_method: {
    type_code: 'default_delivery_method',
    version: '0.4',
    name: 'Ecommerce Default Delivery Method',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'ecommerce_delivery_method',
    dir: 'packages/ecommerce/delivery_methods/default_delivery_method',
    customisation: '0',
    description: 'Default Delivery Method',
    lvl: '2'
  },
  design: {
    type_code: 'design',
    version: '0.5',
    name: 'Design',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'design_area',
    dir: 'core/assets/designs/design',
    customisation: '0',
    description: 'This is the base from which all designs can be parsed and created',
    lvl: '2'
  },
  design_css: {
    type_code: 'design_css',
    version: '0.5',
    name: 'CSS Design File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'design',
    dir: 'core/assets/designs/design_css',
    customisation: '0',
    description: 'This is a CSS asset that is parsed',
    lvl: '3'
  },
  donation: {
    type_code: 'donation',
    version: '0.1',
    name: 'Donation',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/ecommerce/donation',
    customisation: '0',
    description: 'Donation - contains information about a particular donation',
    lvl: '2'
  },
  ecommerce_cart: {
    type_code: 'ecommerce_cart',
    version: '0.5',
    name: 'Cart',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'listing_engine',
    dir: 'packages/ecommerce/ecommerce_cart',
    customisation: '0',
    description: 'Cart object for E-Commerce package',
    lvl: '3'
  },
  ecommerce_checkout: {
    type_code: 'ecommerce_checkout',
    version: '0.4',
    name: 'Checkout Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/ecommerce/ecommerce_checkout',
    customisation: '0',
    description: 'Checkout page to complete an order in an e-commerce system',
    lvl: '2'
  },
  excel_doc: {
    type_code: 'excel_doc',
    version: '0.1',
    name: 'MS Excel Document',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/excel_doc',
    customisation: '0',
    description: 'Specialised type of File asset for Microsoft Excel (.xls) documents.',
    lvl: '2'
  },
  file: {
    type_code: 'file',
    version: '0.5',
    name: 'File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/files/file',
    customisation: '0',
    description: 'Files let you store upload, store and use a file in the system',
    lvl: '1'
  },
  file_bridge: {
    type_code: 'file_bridge',
    version: '0.3',
    name: 'File Bridge',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/filesystem/file_bridge',
    customisation: '0',
    description: 'The file bridge',
    lvl: '1'
  },
  flv_file: {
    type_code: 'flv_file',
    version: '0.1',
    name: 'FLV File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/flv_file',
    customisation: '0',
    description: 'Specialised type of File asset for Flash Video (FLV) files.',
    lvl: '2'
  },
  folder: {
    type_code: 'folder',
    version: '0.1',
    name: 'Folder',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/folder',
    customisation: '0',
    description: 'Folder Object, can link to ANY type of asset, therefore is useful for categorising the assets in the backend',
    lvl: '1'
  },
  funnelback_rest_search_page: {
    type_code: 'funnelback_rest_search_page',
    version: '0.1',
    name: 'Funnelback REST Search Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_rest_resource',
    dir: 'packages/funnelback/page_templates/funnelback_rest_search_page',
    customisation: '0',
    description: 'Funnelback page based on REST Resource Page',
    lvl: '3'
  },
  funnelback_search_log_report: {
    type_code: 'funnelback_search_log_report',
    version: '0.1',
    name: 'Funnelback Search Log Report',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'report',
    dir: 'packages/funnelback/log_reports/funnelback_search_log_report',
    customisation: '0',
    description: 'A report that analyses the funnelback\'s logs',
    lvl: '3'
  },
  funnelback_search_page: {
    type_code: 'funnelback_search_page',
    version: '0.2',
    name: 'Funnelback Search Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'listing_engine',
    dir: 'packages/funnelback/page_templates/funnelback_search_page',
    customisation: '0',
    description: 'Funnelback Search Page asset; provides a front-end interface to search a Funnelback server',
    lvl: '3'
  },
  google_map: {
    type_code: 'google_map',
    version: '0.1',
    name: 'Google Map',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_asset_listing',
    dir: 'packages/google_maps/google_map',
    customisation: '0',
    description: 'This asset hold the longitude, lattitude and description of a particular location.',
    lvl: '4'
  },
  google_map_location: {
    type_code: 'google_map_location',
    version: '0.1',
    name: 'Google Map Location',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/google_maps/google_map_location',
    customisation: '0',
    description: 'This asset hold the longitude, lattitude and description of a particular location.',
    lvl: '1'
  },
  image: {
    type_code: 'image',
    version: '0.4',
    name: 'Image',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/image',
    customisation: '0',
    description: 'Images let you upload, store and use an image in the system',
    lvl: '2'
  },
  ipb_bridge: {
    type_code: 'ipb_bridge',
    version: '0.1',
    name: 'IPB Bridge',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/ipb/ipb_bridge',
    customisation: '0',
    description: 'Provides a bridge between the MySource system and Invision Power Board users',
    lvl: '1'
  },
  js_api: {
    type_code: 'js_api',
    version: '0.6',
    name: 'Javascript API',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/web_services/js_api',
    customisation: '0',
    description: 'The API contains a number of functions which is exposed to allow external system to do operations in Matrix',
    lvl: '2'
  },
  js_file: {
    type_code: 'js_file',
    version: '0.1',
    name: 'JS File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/js_file',
    customisation: '0',
    description: 'Specialised type of File asset for JS Files',
    lvl: '2'
  },
  layout: {
    type_code: 'layout',
    version: '0.2',
    name: 'Simple Edit Layout',
    instantiable: '1',
    allowed_access: 'system_user',
    parent_type: 'bodycopy',
    dir: 'core/assets/layout',
    customisation: '0',
    description: 'Simple Edit Layouts are used to customise the look and feel of asset\'s simple edit interface',
    lvl: '2'
  },
  ldap_bridge: {
    type_code: 'ldap_bridge',
    version: '0.5',
    name: 'LDAP Bridge',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/ldap/ldap_bridge',
    customisation: '0',
    description: 'Provides a bridge between the MySource system and an LDAP directory',
    lvl: '1'
  },
  link: {
    type_code: 'link',
    version: '0.1',
    name: 'Link',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/link',
    customisation: '0',
    description: 'Link object presents an HTML Link in Matrix',
    lvl: '1'
  },
  metadata_schema: {
    type_code: 'metadata_schema',
    version: '0.4',
    name: 'Metadata Schema',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'folder',
    dir: 'core/assets/metadata/metadata_schema',
    customisation: '0',
    description: 'Metadata Schema, define a schema for metadata to be attached to assets in the system',
    lvl: '2'
  },
  mp3_file: {
    type_code: 'mp3_file',
    version: '0.1',
    name: 'MP3 File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/mp3_file',
    customisation: '0',
    description: 'Specialised type of File asset for MP3 Files.',
    lvl: '2'
  },
  news_item: {
    type_code: 'news_item',
    version: '0.3',
    name: 'News Item',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/news/news_item',
    customisation: '0',
    description: 'An invidual news item, to be used in a list',
    lvl: '2'
  },
  online_quiz_question_group: {
    type_code: 'online_quiz_question_group',
    version: '0.2',
    name: 'Online Quiz Question Group',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'folder',
    dir: 'packages/cms/page_templates/page_online_quiz/online_quiz_question_group',
    customisation: '0',
    description: 'A group to house Online Quiz Questions. Provides score range categorisation and customisable responses for each category.',
    lvl: '2'
  },
  online_quiz_question_multichoice: {
    type_code: 'online_quiz_question_multichoice',
    version: '0.3',
    name: 'Online Quiz Multiple-Choice Question',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'online_quiz_question',
    dir: 'packages/cms/page_templates/page_online_quiz/online_quiz_questions/online_quiz_question_multichoice',
    customisation: '0',
    description: 'Generic question for the Online Quiz',
    lvl: '2'
  },
  page_account_manager: {
    type_code: 'page_account_manager',
    version: '0.6',
    name: 'Account Manager Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_asset_builder',
    dir: 'packages/cms/page_templates/page_account_manager',
    customisation: '0',
    description: 'Account Manager Page, users can edit their details, create accounts, join groups etc',
    lvl: '3'
  },
  page_asset_builder: {
    type_code: 'page_asset_builder',
    version: '0.9',
    name: 'Asset Builder Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_asset_builder',
    customisation: '0',
    description: 'Asset Builder Page, a template to add assets from the frontend',
    lvl: '2'
  },
  page_asset_listing: {
    type_code: 'page_asset_listing',
    version: '0.16',
    name: 'Asset Listing Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'listing_engine',
    dir: 'packages/cms/page_templates/page_asset_listing',
    customisation: '0',
    description: 'Lists sub asset or children of an asset is a sortable list format or an A-Z listing',
    lvl: '3'
  },
  page_calendar: {
    type_code: 'page_calendar',
    version: '0.9',
    name: 'Calendar Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/calendar/page_templates/page_calendar',
    customisation: '0',
    description: 'Calendar Page, users can display Calendar Event type assets in the form of a daily, weekly, monthly or annual calendar (in traditional or listing formats) using this asset.',
    lvl: '2'
  },
  page_calendar_events_search: {
    type_code: 'page_calendar_events_search',
    version: '0.1',
    name: 'Calendar Events Search Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'search_page',
    dir: 'packages/calendar/page_templates/page_calendar_events_search',
    customisation: '0',
    description: 'Users can search Calendar Event type assets using different seearch filters.',
    lvl: '4'
  },
  page_calendar_restricted: {
    type_code: 'page_calendar_restricted',
    version: '0.3',
    name: 'Restricted-Period Calendar Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_calendar_rolling',
    dir: 'packages/calendar/page_templates/page_calendar_restricted',
    customisation: '0',
    description: 'Displays calendar events within a specified date range',
    lvl: '3'
  },
  page_calendar_rolling: {
    type_code: 'page_calendar_rolling',
    version: '0.4',
    name: 'Rolling Calendar Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/calendar/page_templates/page_calendar_rolling',
    customisation: '0',
    description: 'Rolling Calendar Page, displays events for a specified interval relative to the current day',
    lvl: '2'
  },
  page_custom_form: {
    type_code: 'page_custom_form',
    version: '0.2',
    name: 'Custom Form',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_custom_form',
    customisation: '0',
    description: 'Custom Form is a powerful form-building template',
    lvl: '2'
  },
  page_custom_form_ecommerce: {
    type_code: 'page_custom_form_ecommerce',
    version: '0.1',
    name: 'Ecommerce Form Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_custom_form',
    dir: 'packages/ecommerce/page_templates/page_custom_form_ecommerce',
    customisation: '0',
    description: 'Ecommerce Form is a form building template with e-commerce functionality',
    lvl: '3'
  },
  page_decision_tree: {
    type_code: 'page_decision_tree',
    version: '0.2',
    name: 'Decision Tree',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_decision_tree',
    customisation: '0',
    description: 'A Decision Tree of Questions.',
    lvl: '2'
  },
  page_hit_count_listing: {
    type_code: 'page_hit_count_listing',
    version: '0.1',
    name: 'Hit Count Listing Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'listing_engine',
    dir: 'packages/data/page_templates/page_hit_count_listing',
    customisation: '0',
    description: 'Lists the number of hits for specified assets which meet specified criteria',
    lvl: '3'
  },
  page_link_manager: {
    type_code: 'page_link_manager',
    version: '0.2',
    name: 'Link Manager Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_asset_listing',
    dir: 'packages/cms/page_templates/page_link_manager',
    customisation: '0',
    description: 'Provides the frontend ability to manage user links to folders and user groups',
    lvl: '4'
  },
  page_multiple_page: {
    type_code: 'page_multiple_page',
    version: '0.1',
    name: 'Multiple Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_multiple_page',
    customisation: '0',
    description: 'Multiple Page, Contains many child pages all controlled by it',
    lvl: '2'
  },
  page_online_quiz: {
    type_code: 'page_online_quiz',
    version: '0.3',
    name: 'Online Quiz',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_asset_listing',
    dir: 'packages/cms/page_templates/page_online_quiz',
    customisation: '0',
    description: 'An online quiz',
    lvl: '4'
  },
  page_password_reset: {
    type_code: 'page_password_reset',
    version: '0.1',
    name: 'Password Reset Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_password_reset',
    customisation: '0',
    description: 'Password Reset Page, in the case that a user has forgotten their password, this page can be used to reset it',
    lvl: '2'
  },
  page_poll: {
    type_code: 'page_poll',
    version: '0.3',
    name: 'Online Poll',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_poll',
    customisation: '0',
    description: 'Online Poll.',
    lvl: '2'
  },
  page_redirect: {
    type_code: 'page_redirect',
    version: '0.4',
    name: 'Redirect Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_redirect',
    customisation: '0',
    description: 'Redirect Page, a simple page template to redirect the user to another location',
    lvl: '2'
  },
  page_related_asset_listing: {
    type_code: 'page_related_asset_listing',
    version: '0.1',
    name: 'Related Asset Listing Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_asset_listing',
    dir: 'packages/cms/page_templates/page_related_asset_listing',
    customisation: '0',
    description: 'Lists related asset as a sortable list format or an A-Z listing',
    lvl: '4'
  },
  page_remote_content: {
    type_code: 'page_remote_content',
    version: '1.7',
    name: 'Remote Content',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_remote_content',
    customisation: '0',
    description: 'This page template allows you to retrieve a remote page without it being inside an iFrame',
    lvl: '2'
  },
  page_rest_resource: {
    type_code: 'page_rest_resource',
    version: '0.1',
    name: 'REST Resource',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/web_services/rest/page_templates/page_rest_resource',
    customisation: '0',
    description: 'REST Resource',
    lvl: '2'
  },
  page_rest_resource_js: {
    type_code: 'page_rest_resource_js',
    version: '0.1',
    name: 'REST Resource JavaScript',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_rest_resource',
    dir: 'packages/web_services/rest/page_templates/page_rest_resource_js',
    customisation: '0',
    description: 'REST Resource with JavaScript Processing',
    lvl: '3'
  },
  page_rest_resource_oauth_session: {
    type_code: 'page_rest_resource_oauth_session',
    version: '0.1',
    name: 'REST Resource OAuth Session',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_rest_resource',
    dir: 'packages/web_services/rest/page_templates/page_rest_resource_oauth_session',
    customisation: '0',
    description: 'OAuth authentication set in session',
    lvl: '3'
  },
  page_rest_resource_oauth_two_legged: {
    type_code: 'page_rest_resource_oauth_two_legged',
    version: '0.1',
    name: 'REST Resource OAuth 2 Legged',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_rest_resource',
    dir: 'packages/web_services/rest/page_templates/page_rest_resource_oauth_two_legged',
    customisation: '0',
    description: '2 legged OAuth authentication',
    lvl: '3'
  },
  page_rss_feed: {
    type_code: 'page_rss_feed',
    version: '0.1',
    name: 'RSS Feed',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/news/page_rss_feed',
    customisation: '0',
    description: 'This is used to generate the RSS Feeds',
    lvl: '2'
  },
  page_site_map: {
    type_code: 'page_site_map',
    version: '0.3',
    name: 'Site Map',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_site_map',
    customisation: '0',
    description: 'Site Map, Shows a tree stucture of the pages in the current site.',
    lvl: '2'
  },
  page_standard: {
    type_code: 'page_standard',
    version: '0.2',
    name: 'Standard Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'core/assets/page_templates/page_standard',
    customisation: '0',
    description: 'Standard Page, contains a bodycopy for simple content',
    lvl: '2'
  },
  page_tag_listing: {
    type_code: 'page_tag_listing',
    version: '0.1',
    name: 'Tag Listing Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_asset_listing',
    dir: 'packages/cms/page_templates/page_tag_listing',
    customisation: '0',
    description: 'Tag Listing',
    lvl: '4'
  },
  page_upcoming_events_list: {
    type_code: 'page_upcoming_events_list',
    version: '0.3',
    name: 'Upcoming Events List',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/calendar/page_templates/page_upcoming_events_list',
    customisation: '0',
    description: 'Shows a certain number of upcoming events',
    lvl: '2'
  },
  page_user_group_manager: {
    type_code: 'page_user_group_manager',
    version: '0.1',
    name: 'User Group Manager Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/cms/page_templates/page_user_group_manager',
    customisation: '0',
    description: 'Provides the frontend ability to manage user/user group relation ',
    lvl: '2'
  },
  page_whats_new: {
    type_code: 'page_whats_new',
    version: '0.5',
    name: 'Whats New',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'listing_engine',
    dir: 'packages/cms/page_templates/page_whats_new',
    customisation: '0',
    description: 'Lists assets by date',
    lvl: '3'
  },
  paint_layout_page: {
    type_code: 'paint_layout_page',
    version: '0.1',
    name: 'Paint Layout',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_standard',
    dir: 'core/assets/paint_layout/paint_layout_page',
    customisation: '0',
    description: 'Paint Layout is used to customise the appearance of different types of asset.',
    lvl: '3'
  },
  payment_gateway_datacash: {
    type_code: 'payment_gateway_datacash',
    version: '0.1',
    name: 'Datacash Payment Gateway',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'payment_gateway',
    dir: 'packages/ecommerce/payment_gateway_types/payment_gateway_datacash',
    customisation: '0',
    description: 'Payment Gateway for Datacash payment system',
    lvl: '3'
  },
  payment_gateway_dps: {
    type_code: 'payment_gateway_dps',
    version: '0.1',
    name: 'DPS Payment Gateway',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'payment_gateway',
    dir: 'packages/ecommerce/payment_gateway_types/payment_gateway_dps',
    customisation: '0',
    description: 'Payment Gateway for Direct Payment Solution payment system',
    lvl: '3'
  },
  payment_gateway_esec: {
    type_code: 'payment_gateway_esec',
    version: '0.4',
    name: 'SecurePay eSec Payment Gateway',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'payment_gateway',
    dir: 'packages/ecommerce/payment_gateway_types/payment_gateway_esec',
    customisation: '0',
    description: 'Payment Gateway for SecurePay\'s eSec payments system',
    lvl: '3'
  },
  payment_gateway_payflow: {
    type_code: 'payment_gateway_payflow',
    version: '0.1',
    name: 'PayPal Payflow Pro Payment Gateway',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'payment_gateway',
    dir: 'packages/ecommerce/payment_gateway_types/payment_gateway_payflow',
    customisation: '0',
    description: 'Payment Gateway for the Paypal\'s Payflow Pro payment system',
    lvl: '3'
  },
  payment_gateway_paypal_express: {
    type_code: 'payment_gateway_paypal_express',
    version: '0.1',
    name: 'PayPal Express Checkout Payment Gateway',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'payment_gateway',
    dir: 'packages/ecommerce/payment_gateway_types/payment_gateway_paypal_express',
    customisation: '0',
    description: 'Payment Gateway for the Paypal Express Checkout payment system',
    lvl: '3'
  },
  payment_gateway_sagepay: {
    type_code: 'payment_gateway_sagepay',
    version: '0.1',
    name: 'SagePay Payment Gateway',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'payment_gateway',
    dir: 'packages/ecommerce/payment_gateway_types/payment_gateway_sagepay',
    customisation: '0',
    description: 'Payment Gateway for Sage Pay payment system',
    lvl: '3'
  },
  payment_gateway_securepay: {
    type_code: 'payment_gateway_securepay',
    version: '0.1',
    name: 'SecurePay Direct Post Payment Gateway',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'payment_gateway',
    dir: 'packages/ecommerce/payment_gateway_types/payment_gateway_securepay',
    customisation: '0',
    description: 'Payment Gateway for the SecurePay Direct Post payment system',
    lvl: '3'
  },
  payment_gateway_utransact: {
    type_code: 'payment_gateway_utransact',
    version: '0.1',
    name: 'UTransact Payment Gateway',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'payment_gateway',
    dir: 'packages/ecommerce/payment_gateway_types/payment_gateway_utransact',
    customisation: '0',
    description: 'Payment Gateway for Direct Payment Solution payment system',
    lvl: '3'
  },
  paypal_business_account: {
    type_code: 'paypal_business_account',
    version: '0.1',
    name: 'Paypal Business Account',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/ecommerce/paypal/paypal_business_account',
    customisation: '0',
    description: 'This asset represents a Paypal Business Account that can accept payments',
    lvl: '1'
  },
  paypal_configuration: {
    type_code: 'paypal_configuration',
    version: '0.1',
    name: 'Paypal Configuration',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/ecommerce/paypal/paypal_configuration',
    customisation: '0',
    description: 'This asset provides all the configuration fields needed for Paypal assets',
    lvl: '1'
  },
  paypal_ipn_receiver: {
    type_code: 'paypal_ipn_receiver',
    version: '0.1',
    name: 'Paypal IPN Receiver',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/ecommerce/paypal/paypal_ipn_receiver',
    customisation: '0',
    description: 'This is an Instant Payment Notification (IPN) Receiver that receives a POST request from Paypal after a complete payment process',
    lvl: '2'
  },
  paypal_payment_button: {
    type_code: 'paypal_payment_button',
    version: '0.1',
    name: 'Paypal Payment Button',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/ecommerce/paypal/paypal_payment_button',
    customisation: '0',
    description: 'This is an encrypted Paypal payment button',
    lvl: '2'
  },
  pdf_file: {
    type_code: 'pdf_file',
    version: '0.2',
    name: 'PDF File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/pdf_file',
    customisation: '0',
    description: 'Specialised type of File asset for Portable Document Format (.pdf, a.k.a Adobe Acrobat) files.',
    lvl: '2'
  },
  powerpoint_doc: {
    type_code: 'powerpoint_doc',
    version: '0.1',
    name: 'MS PowerPoint Document',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/powerpoint_doc',
    customisation: '0',
    description: 'Specialised type of File asset for Microsoft PowerPoint (.ppt) documents.',
    lvl: '2'
  },
  product: {
    type_code: 'product',
    version: '0.2',
    name: 'Product',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/ecommerce/product',
    customisation: '0',
    description: 'Product - contains information about a particular product',
    lvl: '2'
  },
  promotional_code: {
    type_code: 'promotional_code',
    version: '0.1',
    name: 'Promotional Code',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/ecommerce/promotion/promotional_code',
    customisation: '0',
    description: 'Promotional Code asset represents a discount code for products',
    lvl: '1'
  },
  report_asset_counter: {
    type_code: 'report_asset_counter',
    version: '0.1',
    name: 'Asset Counter Report',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'report',
    dir: 'core/assets/reports/asset_counter',
    customisation: '0',
    description: 'Counts the number of child assets',
    lvl: '3'
  },
  report_asset_statuses: {
    type_code: 'report_asset_statuses',
    version: '0.1',
    name: 'Asset Statuses Report',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'report',
    dir: 'packages/cms/reports/report_asset_statuses',
    customisation: '0',
    description: 'Reports assets according to status and time of last status change',
    lvl: '3'
  },
  report_incomplete_metadata: {
    type_code: 'report_incomplete_metadata',
    version: '0.2',
    name: 'Incomplete Metadata Report',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'report',
    dir: 'core/assets/reports/incomplete_metadata',
    customisation: '0',
    description: 'Incomplete Metadata Report, displays a report of assets with incomplete metadata',
    lvl: '3'
  },
  report_links: {
    type_code: 'report_links',
    version: '0.3',
    name: 'Links Report',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'report',
    dir: 'packages/cms/reports/report_links',
    customisation: '0',
    description: 'Links Report, displays a report of internal and external links in content with a description if they are broken',
    lvl: '3'
  },
  report_safe_trash: {
    type_code: 'report_safe_trash',
    version: '0.1',
    name: 'Safe Trash Report',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'report',
    dir: 'core/assets/reports/report_safe_trash',
    customisation: '0',
    description: 'Safe Trash Report, displays a report of assets currently marked to be safe-trashed when possible',
    lvl: '3'
  },
  role: {
    type_code: 'role',
    version: '0.1',
    name: 'Role',
    instantiable: '1',
    allowed_access: 'administrator',
    parent_type: 'user_group',
    dir: 'core/assets/users/role',
    customisation: '0',
    description: 'A user group style asset which enables contextual permissions',
    lvl: '3'
  },
  rtf_file: {
    type_code: 'rtf_file',
    version: '0.1',
    name: 'RTF File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/rtf_file',
    customisation: '0',
    description: 'Specialised type of File asset for RTF Files (.rtf)',
    lvl: '2'
  },
  saml_account_manager: {
    type_code: 'saml_account_manager',
    version: '0.1',
    name: 'SAML Account Manager',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page_asset_builder',
    dir: 'packages/saml/page_templates/saml_account_manager',
    customisation: '0',
    description: 'SAML Account Manager',
    lvl: '3'
  },
  search_folder: {
    type_code: 'search_folder',
    version: '0.4',
    name: 'Search Folder',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/search/search_folder',
    customisation: '0',
    description: 'Provides a customisable quick search interface for the asset map',
    lvl: '1'
  },
  search_list: {
    type_code: 'search_list',
    version: '0.4',
    name: 'Search List',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'listing_engine',
    dir: 'packages/search/search_list',
    customisation: '0',
    description: 'Lists search terms in an asset listing style and performs a search when the term is clicked',
    lvl: '3'
  },
  search_log_report: {
    type_code: 'search_log_report',
    version: '0.1',
    name: 'Search Log Report',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'log_report',
    dir: 'packages/search/log_reports/search_log_report',
    customisation: '0',
    description: 'A report that analyses the search manager\'s logs',
    lvl: '4'
  },
  search_page: {
    type_code: 'search_page',
    version: '0.26',
    name: 'Search Page',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'listing_engine',
    dir: 'packages/search/search_page',
    customisation: '0',
    description: 'Search Page asset; provides a front-end interface to the search manager so a user can search for assets within a MySource Matrix system.',
    lvl: '3'
  },
  sharepoint_connector: {
    type_code: 'sharepoint_connector',
    version: '0.1',
    name: 'Sharepoint Connector',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/sharepoint/sharepoint_connector',
    customisation: '0',
    description: 'This asset is used to store the connection information to a Sharepoint system.',
    lvl: '1'
  },
  sharepoint_saved_search: {
    type_code: 'sharepoint_saved_search',
    version: '0.1',
    name: 'Sharepoint Saved Search',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/sharepoint/sharepoint_saved_search',
    customisation: '0',
    description: 'This is used to establish connectivity with a Sharepoint system',
    lvl: '2'
  },
  simple_edit_user: {
    type_code: 'simple_edit_user',
    version: '0.1',
    name: 'Simple Edit User',
    instantiable: '1',
    allowed_access: 'system_user',
    parent_type: 'user',
    dir: 'core/assets/users/simple_edit_user',
    customisation: '0',
    description: 'Simple Edit Users have access only to the simple edit interface',
    lvl: '2'
  },
  site: {
    type_code: 'site',
    version: '0.2',
    name: 'Site',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'folder',
    dir: 'core/assets/site',
    customisation: '0',
    description: 'Sites are the base points for any frontend web system',
    lvl: '2'
  },
  site_network: {
    type_code: 'site_network',
    version: '0.1',
    name: 'Site Network',
    instantiable: '1',
    allowed_access: 'system_user',
    parent_type: 'folder',
    dir: 'core/assets/site_network',
    customisation: '0',
    description: 'Creates a network of sites and allows for sessions to crosss domains within the network',
    lvl: '2'
  },
  soap_api_asset_service: {
    type_code: 'soap_api_asset_service',
    version: '0.1',
    name: 'SOAP API Asset Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_asset_service',
    customisation: '0',
    description: 'This API contain functions call to manipulate Matrix assets.',
    lvl: '2'
  },
  soap_api_design_lookup_service: {
    type_code: 'soap_api_design_lookup_service',
    version: '0.1',
    name: 'SOAP API Design Lookup Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_design_lookup_service',
    customisation: '0',
    description: 'This API contain functions call to perform design and lookup operations in Matrix.',
    lvl: '2'
  },
  soap_api_file_retrieval_service: {
    type_code: 'soap_api_file_retrieval_service',
    version: '0.1',
    name: 'SOAP API File Retrieval Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_file_retrieval_service',
    customisation: '0',
    description: 'This API contain functions call to transfer files from Matrix.',
    lvl: '2'
  },
  soap_api_link_service: {
    type_code: 'soap_api_link_service',
    version: '0.1',
    name: 'SOAP API Link Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_link_service',
    customisation: '0',
    description: 'This API contain functions call to perform linking operations in Matrix.',
    lvl: '2'
  },
  soap_api_metadata_service: {
    type_code: 'soap_api_metadata_service',
    version: '0.1',
    name: 'SOAP API Metadata Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_metadata_service',
    customisation: '0',
    description: 'This API contain functions call to perform metadata actions in Matrix.',
    lvl: '2'
  },
  soap_api_permission_role_service: {
    type_code: 'soap_api_permission_role_service',
    version: '0.1',
    name: 'SOAP API Permission And Role Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_permission_role_service',
    customisation: '0',
    description: 'This API contain functions call to perform permission and role operations in Matrix.',
    lvl: '2'
  },
  soap_api_search_service: {
    type_code: 'soap_api_search_service',
    version: '0.1',
    name: 'SOAP API Search Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_search_service',
    customisation: '0',
    description: 'This API contain functions call to search contents within Matrix.',
    lvl: '2'
  },
  soap_api_system_service: {
    type_code: 'soap_api_system_service',
    version: '0.1',
    name: 'SOAP API System Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_system_service',
    customisation: '0',
    description: 'This API contain functions call about core Matrix system.',
    lvl: '2'
  },
  soap_api_workflow_service: {
    type_code: 'soap_api_workflow_service',
    version: '0.1',
    name: 'SOAP API Workflow Service',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'soap_api',
    dir: 'packages/web_services/api/soap_api_workflow_service',
    customisation: '0',
    description: 'This API contain functions call to perform workflow actions in Matrix.',
    lvl: '2'
  },
  soap_server: {
    type_code: 'soap_server',
    version: '0.1',
    name: 'Soap Server',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'page',
    dir: 'packages/web_services/soap_server',
    customisation: '0',
    description: 'Soap Server, displaying available API.',
    lvl: '2'
  },
  structured_asset_info: {
    type_code: 'structured_asset_info',
    version: '0.1',
    name: 'Structured Asset Report',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'report',
    dir: 'core/assets/reports/structured_asset_info',
    customisation: '0',
    description: 'Reports asset information according to configuration in tree structure',
    lvl: '3'
  },
  system_user: {
    type_code: 'system_user',
    version: '0.1',
    name: 'System Administrator',
    instantiable: '1',
    allowed_access: 'root_user',
    parent_type: 'backend_user',
    dir: 'core/assets/system/system_user',
    customisation: '0',
    description: 'System Administrator - one step from holiness',
    lvl: '3'
  },
  text_file: {
    type_code: 'text_file',
    version: '0.1',
    name: 'Text File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/text_file',
    customisation: '0',
    description: 'Specialised type of File asset for Text Files (eg. .txt, .js, .css)',
    lvl: '2'
  },
  thesaurus: {
    type_code: 'thesaurus',
    version: '0.4',
    name: 'Thesaurus',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/thesaurus',
    customisation: '0',
    description: 'Thesaurus Asset for storing terms and relate them to one another (ANSI-compliant)',
    lvl: '1'
  },
  thesaurus_term: {
    type_code: 'thesaurus_term',
    version: '0.2',
    name: 'Thesaurus Term',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/thesaurus_term',
    customisation: '0',
    description: 'Asset Representing one term in the thesaurus (ANSI-compliant)',
    lvl: '1'
  },
  thumbnail: {
    type_code: 'thumbnail',
    version: '0.1',
    name: 'Thumbnail',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'image',
    dir: 'core/assets/files/thumbnail',
    customisation: '0',
    description: 'Thumbnails let you upload, store and use a thumbnail in the system',
    lvl: '3'
  },
  trigger: {
    type_code: 'trigger',
    version: '0.4',
    name: 'Trigger',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/system/triggers/trigger',
    customisation: '0',
    description: 'Trigger',
    lvl: '1'
  },
  trim_connector: {
    type_code: 'trim_connector',
    version: '0.1',
    name: 'TRIM Connector',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/trim/trim_connector',
    customisation: '0',
    description: 'This asset is used to store the connection information to a TRIM system.',
    lvl: '1'
  },
  trim_saved_search: {
    type_code: 'trim_saved_search',
    version: '0.3',
    name: 'TRIM Saved Search',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source',
    dir: 'packages/trim/trim_saved_search',
    customisation: '0',
    description: 'This is used to establish connectivity with a TRIM system',
    lvl: '2'
  },
  user: {
    type_code: 'user',
    version: '0.4',
    name: 'User',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/users/user',
    customisation: '0',
    description: 'User Object, if you want to do anything in the backend, you need to login and this is you object',
    lvl: '1'
  },
  user_group: {
    type_code: 'user_group',
    version: '0.1',
    name: 'User Group',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'folder',
    dir: 'core/assets/users/user_group',
    customisation: '0',
    description: 'A folder for users and other user groups',
    lvl: '2'
  },
  video_file: {
    type_code: 'video_file',
    version: '0.1',
    name: 'Video File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/video_file',
    customisation: '0',
    description: 'Specialised type of File asset for Video Files.',
    lvl: '2'
  },
  weatherco_feed: {
    type_code: 'weatherco_feed',
    version: '0.1',
    name: 'Weather Company Feed',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'data_source_xml',
    dir: 'packages/data/weatherco_feed',
    customisation: '0',
    description: 'Provides ability to read a subscription-based XML feed provided by The Weather Company.',
    lvl: '3'
  },
  word_doc: {
    type_code: 'word_doc',
    version: '0.1',
    name: 'MS Word Document',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/word_doc',
    customisation: '0',
    description: 'Specialised type of File asset for Microsoft Word (.doc, .dot) documents.',
    lvl: '2'
  },
  workflow_bundle: {
    type_code: 'workflow_bundle',
    version: '0.1',
    name: 'Bundle',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'core/assets/workflow/workflow_bundle',
    customisation: '0',
    description: 'Workflow Bundle. An asset that allows a bunch of otherwise unrelated assets with workflow to go through workflow together.',
    lvl: '1'
  },
  workflow_schema: {
    type_code: 'workflow_schema',
    version: '0.2',
    name: 'Workflow Schema',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'folder',
    dir: 'core/assets/workflow/workflow_schema',
    customisation: '0',
    description: 'Workflow Schema, define a schema for workflow to be attached to assets in the system',
    lvl: '2'
  },
  xml_file: {
    type_code: 'xml_file',
    version: '0.1',
    name: 'XML File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/xml_file',
    customisation: '0',
    description: 'Specialised type of File asset for XML Files (eg. .xml)',
    lvl: '2'
  },
  xml_user_bridge: {
    type_code: 'xml_user_bridge',
    version: '0.1',
    name: 'XML User Bridge',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'asset',
    dir: 'packages/data/xml_user_bridge',
    customisation: '0',
    description: 'Exposes user assets based on data from an XML file',
    lvl: '1'
  },
  xsl_file: {
    type_code: 'xsl_file',
    version: '0.1',
    name: 'XSL File',
    instantiable: '1',
    allowed_access: 'backend_user',
    parent_type: 'file',
    dir: 'core/assets/files/xsl_file',
    customisation: '0',
    description: 'Specialised type of File asset for XSL Files (eg. .xsl)',
    lvl: '2'
  }
};
